### ISSUE TITLE
MacOS catalina support

### ISSUE THREAD

**Issue by Stevemoretz** [aaaamirabbas/nekoray-macos#4]
You have macOS 10.15.7. The application requires macOS 12.6 or later, can you add macOS 10.15 support?

**Comment by aaaamirabbas** [comment]
Hi, where did you find out that the last build of version 12.6 are supported later? Do you have links or information or doc in this case? **Do you have an error log?**

You can also create a dedicated Build for yourself according to the commands inside the readme.md file, this is easy (I think the problem will be solving)

**Comment by Stevemoretz** [comment]
I have a macOS 10.15.7 I simply downloaded the build and opened it, and it gave me that error: 

"You have macOS 10.15.7. The application requires macOS 12.6 or later"

Thanks for the suggestion, but felt like it would be a help to you to get this report, 12.6 seems too high after all.

**Comment by aaaamirabbas** [comment]
Thank you for the report and yes will help me and I will consider this in the future, but the problem is that I didn't set any flags or regulations for this and I don't know why it does not support version 12.6 to lower.

My macOS version is 12.6 and the only thing that comes to my mind is that the versions that are dependencies are compatible with this version of macOS.

Please run the script and report it if the problem is solved.

Thank you

**Comment by Stevemoretz** [comment]
> Thank you for the report and yes will help me and I will consider this in the future, but the problem is that I didn't set any flags or regulations for this and I don't know why it does not support version 12.6 to lower.
> 
> My macOS version is 12.6 and the only thing that comes to my mind is that the versions that are dependencies are compatible with this version of macOS.
> 
> Please run the script and report it if the problem is solved.
> 
> Thank you

I couldn't build it using Catalina there is an error, it must still be possible to build with 12 for 10, that's why I went for the github action way and here's a PR draft I made for your repo:
https://github.com/aaaamirabbas/nekoray-macos/pull/5
